In [81]:
#!/usr/bin/env python
import numpy as np
from numpy.linalg import det, inv, matrix_rank
# from sympy import Matrix, symbols, EmptySet
# from sympy.solvers.solveset import linsolve
from copy import copy
from cvxopt.glpk import ilp
from cvxopt import matrix
from itertools import combinations


def get_hermit(dimensions=6, max_minor = 5):
    diag = np.array([1]*(dimensions)).astype('i')
    diag[-1] = max_minor
    pre_last = np.random.randint(max_minor, size=dimensions - 1)
    hermit = np.diag(diag)
    hermit[dimensions-1][:-1] = pre_last
    return hermit


def apply_restrictor(hermit, dimensions=6, max_minor = 5):
    continue_flag = True
    restricted = 0
    while continue_flag:
        restricted = np.append(hermit, np.random.randint(-max_minor, max_minor + 1, size=(1, dimensions)), 0)
        minors = get_minors(restricted)
        continue_flag = not all(minors)
    abs_minors = [abs(m) for m in minors]
    return restricted, min(abs_minors), max(abs_minors)


def minor(arr, i=0):
#     ith row removed
    return arr[np.array(range(i)+range(i+1, arr.shape[0]))[:, np.newaxis],
               np.array(range(arr.shape[1]))]


def get_minors(A):
    return [det(minor(A,i)) for i in xrange(A.shape[0])]
    
    
def is_valid_solution(solution):
    return  any(x for x in solution)


def generate_vertices(cone, b):
    vertices = []
    for i in xrange(cone.shape[0]):
        vertices.append(inv(minor(cone,i)).dot(b[range(i)+range(i+1, b.shape[0])]))
    return vertices 


def full_cycle(dimensions=6, p = 5):
    np.random.seed()
    h = get_hermit(dimensions, p)
    cone, min_m, max_m = apply_restrictor(h, dimensions, p)
    # cone = np.ndarray(cone, dtype=float)
    print cone

    c = cone[-1]
    x = np.zeros(shape=(dimensions,1), dtype=float)
    x[-1] = float(dimensions)/float(p)

    sigma = c.dot(x)  # ( b[n+1])

    f = copy(x)#np.reshape(np.append(x, sigma), newshape=(dimensions + 1, 1))
    f[-1] = float(dimensions + 1)/float(p)

    # print 'f (vector-indicator`s last value): %s' % f[-1]  #  == sol

    if c.dot(f) > sigma:
        print 'f belongs to M={x: cx >= %s}' % sigma
    else:
        print 'f doesn`t belong to M={x: cx >= %s}'% sigma

    target_f = matrix(-np.ones((dimensions + 1,1),dtype=float), tc='d')
    # cycle for changing sigma
    (status,s) = ilp(target_f, 
             G=matrix(-cone, tc='d'),
             h=matrix(-np.append(f, sigma), tc='d'),
    #                  A=matrix(1., (0,6)),b=matrix(1., (0,1)),
             I=set(range(dimensions)),
    #                  B=set()
            )
    if s:
        print 'status: ', status
        return
    
    if status == 'LP relaxation is primal infeasible':
        print 'Primal infeasible'
        return
#     if is_valid_solution(s):
#         for s_s in s:
#             print float(s_s)
#     else:
#         print 'Trivial solution.'
#         for s_s in s:
#             print float(s_s)

    # print matrix_rank(cone)
    # print cone
    b = np.append(f, sigma)
    # print 'dots\n'

    # for i in xrange(cone.shape[0]):
    #     print inv(minor(cone,i)).dot(b[range(i)+range(i+1, b.shape[0])])
    vv = generate_vertices(cone, b)

    width_list = []
    for i,j in combinations(xrange(len(vv)), 2):
    #     print(pair)
        target_f2 = vv[i] - vv[j]
        restrictions = np.concatenate((inv(minor(cone, i).T), -inv(minor(cone, j).T), np.diag(np.ones(len(vv[0])).astype('d'))))
    #     print 'tar'
    #     print matrix(target_f2)
    # #     print restrictions
    #     print 'res'
    #     print matrix(-restrictions, tc='d')
    #     print 'ri'
    #     print matrix(np.zeros(shape=(restrictions.shape[0],1)), tc='d'),
        (status,s) = ilp(matrix(target_f2), 
             G=matrix(-restrictions, tc='d'),
             h=matrix(np.ones(shape=(restrictions.shape[0],1), dtype=np.double), tc='d'),
    # #                  A=matrix(1., (0,6)),b=matrix(1., (0,1)),
             I=set(range(len(vv)-1)),
    # #                  B=set()
            )
    #     print status, is_valid_solution(s)
        if status == 'optimal':
            width_c = abs(target_f2.dot(s)[0])
            if is_valid_solution(s) and width_c > float(0.0000):
                width_list.append(width_c)

    print 'width: ', float(min(width_list))
    print 'dimensions: ', dimensions
    print 'mmin: ', min_m, ' mmax: ',max_m



import multiprocessing
import time
# full_cycle(4,3)
p = multiprocessing.Process(target=full_cycle, args=(10,7))
p.start()
p.join(5)
if p.is_alive():
    print "running... let's kill it..."

    # Terminate
    p.terminate()
    
    p.join()
    

# from concurrent.futures import ProcessPoolExecutor

# def timeout_five(fnc, *args, **kwargs):
#     with ProcessPoolExecutor() as p:
#         f = p.submit(fnc, *args, **kwargs)
#         return f.result(timeout=5)
# timeout_five(full_cycle,4,3)

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  1  0]
 [ 6  5  4  6  5  6  4  5  3  7]
 [-2 -3  5 -6  7  7 -1  4 -6  4]]
f belongs to M={x: cx >= [ 5.71428571]}
width:  4.52332407119e-17
dimensions:  10
mmin:  4.0  mmax:  66.0
